# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 133d8c6d1524a0b7bedcb251ecda0ea216352f128e4af0ae3796348818c908e0be0bb6fd0814a6351add36605cc588ae42f2ac76b2ae59f93a7b88c110dc5f67

test:
  secret_key_base: 37fd6a36c0c3d007604cbacf72c2b3834d7cbb98ec769423907f5843f664b3623eaede60ba4736d2c6b36463fa6e06fd99bc058becf8a35e3d4e5b2cb558df73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
